remotes:
  aws-east-1:
    endpoint: https://us-east-1.amazonaws.com
    region: us-east-1
    access_key: ""
    secret_key: ""
  do-nyc3:
    endpoint: https://nyc3.digitaloceanspaces.com
    region: nyc3
    access_key: ""
    secret_key: ""
