current_remote: "example-mgc"
remotes:
  aws-east-1:
    s3:
      endpoint: https://s3.us-east-1.amazonaws.com
      region: us-east-1
      access_key: ""
      secret_key: ""
  do-nyc3:
    s3:
      endpoint: https://nyc3.digitaloceanspaces.com
      region: us-east-1
      access_key: ""
      secret_key: ""
  example-mgc:
    s3:
      endpoint: https://example.com
      region: us-east-1
      access_key: ""
      secret_key: ""
    mgc:
      access_key: ""
      secret_key: ""
  local:
    swift:
      auth: http://127.0.0.1:8080/auth/v1.0
      user: test:tester
      key: testing
    s3:
      endpoint: http://127.0.0.1:8080
      region: us-east-1
      access_key: "test:tester"
      secret_key: "testing"
