[aws-east-1]
region = "us-east-1"
endpoint = "https://us-east-1.amazonaws.com"
access_key = ""
secret_key = ""

[do-nyc3]
region = "NYC3"
endpoint = "https://nyc3.digitaloceanspaces.com"
access_key = ""
secret_key = ""
