# credentials and endpoints for multiple object storage providers
remotes:
  aws-east-1:
    s3:
      endpoint: https://s3.us-east-1.amazonaws.com
      region: us-east-1
      access_key: ""
      secret_key: ""
  do-nyc3:
    s3:
      endpoint: https://nyc3.digitaloceanspaces.com
      region: us-east-1
      access_key: ""
      secret_key: ""
  example-mgc:
    s3:
      endpoint: https://example.com
      region: ""
      access_key: ""
      secret_key: ""
    mgc:
      region: ""
      access_key: ""
      secret_key: ""
  local:
    swift:
      auth: http://127.0.0.1:8080/auth/v1.0
      user: test:tester
      key: testing
    s3:
      endpoint: http://127.0.0.1:8080
      region: us-east-1
      access_key: "test:tester"
      secret_key: "testing"

# TODO: mgc tool supports only one remote / profile, this config will be deprecated in the future
current_remote: "example-mgc"

# config for a webserver to expose results in a website, see webapp.Dockerfile
webapp:
  nginx:
    listen: 5000
    server_name: localhost
    locations:
      "/":
        root: "/app/results"

# specific remotes for specific test groups
small_set_remotes: "do-nyc3 aws-east-1"

# prometheus write endpoint to send metrics to, if filled will also send prometheus metrics.
prometheus_rw_url: "http://<prometheus-dns-or-ip>:9090/api/v1/write"

# settings for storing the results in the cloud
# XXX: add -s3 in the end of the name because the sync is made with rclone
results_bucket: "aws-east-1-s3:object-storage-tests-results-2024-02"
